### ISSUE TITLE
1.20 Support

### ISSUE THREAD

**Issue by Kitimaa** [Librv/Compressor#12]
Is there a plan to update the mod to 1.20 or is it dead. It would be nice if the mod was updated to this version. I haven't seen any info about whether the mod will be updated or if it's no longer being worked on.

**Comment by Librv** [comment]
Not dead, working on Chassis first things first, with that ironed out Compressor is done in less than 10 minutes.

**Comment by Kitimaa** [comment]
> Not dead, working on Chassis first things first, with that ironed out Compressor is done in less than 10 minutes.

Awesome, thanks for all the great work and mods btw. Any chance there is a time frame, I'm working on building a 1.20 modpack and would definitely like to use the mod.

**Comment by Librv** [comment]
Next tuesday would be the earliest date if nothing else pops up.

**Comment by Librv** [comment]
Done, both on [CurseForge](https://curseforge.com/minecraft/mc-mods/compressor/files) and [Modrinth](https://modrinth.com/mod/compressor)
