### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by CassieRoseZA** [Librv/Compressor#13]
Recently im not sure what changed but i can't use this mod on my server anymore it just completely fails to start and gives the error of 
[11:58:23] [main/ERROR]: Invalid path, the ResourcePack folder may not exist for "compressor"
[11:58:23] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.getFileSystem()" because "path" is null

**Comment by Librv** [comment]
Can you provide a mod list?

**Comment by CassieRoseZA** [comment]
KubeJS
Farming for Blockheads
Architectury
MaLiLib
Rechiseled
Lets Do Api
HD Skins
BotanyPots
Resourceful Lib
ExtendedAE
NotEnoughAnimations
Extended Drawers
Auth Me
Faux-Custom-Entity-Data
Nature's Compass
Alloy Forgery
Bookshelf
DragonLoot
Chipped
Balm
Better Beds
Respite Creators
Iris
Factory API
Puzzle
spark
Packed Up
Polymorph
Torcherino
YUNG's API
Botarium
Hole Filler Mod
Terrestria
Modern Industrialization
Adorn
Bad Wither No Cookie Reloaded
Comforts
Botania
Prefabricated
More Villagers
ME Requester
Update ME!
EnchantmentDescriptions
Indium
MEGA Cells
Fabric API
Forge Config API Port
Applied Energistics 2
Origins: Classes
Farmer's Knives
YUNG's Better Dungeons
Controlling For Fabric
Lootr
Mod Menu
Additional Additions
BetterF3
Tech Reborn
Rhino
Entity Texture Features
Universal Sawmill
Pehkui
CreativeCore
Better Combat
Patchouli
wthit
GeckoLibIrisCompat
CIT Resewn
Bakery
Roughly Enough Items
Framework
MidnightControls Extra
Farmer's Respite
MidnightLib
Seamless
FerriteCore
Trinkets
Sodium Extra
Bartering Station
BotanyPotsTiers
Traveler's Backpack
Player Animator
EpheroLib
Cadmus
Boosted Brightness
Tesseract
Create: New Age
Dank Storage
Item Collectors
MidnightControls
Revelationary
BlossomLib
Wood you Dye
Better Furnaces Reforged
Abridged
BlossomEnderChest
Command Config Lib
Dehydration
MiniHUD
ShetiPhianCore
OptiGUI
Croptopia
AppleSkin
Enchanting Infuser
Offline Daylight Stop
Twitch Chat Bridge
Wormhole (Portals)
Reborn Core
Another Furniture
Argonauts
Reimagined Trims
Flat Bedrock
YetAnotherConfigLib
Just Another Mining Dimension
Roughly Enough Professions
Artifacts
Tweakeroo
Macaw's Lights and Lamps
Origins
Skniro's GrowableOres
Cooking for Blockheads
Fabric Language Kotlin
FTB Ultimine
Be Proud
Lighty
Styled Chat
YOSBR
Softer Pastels
Searchables
LazyDFU
Classic Minecraft Icon
Farmer's Delight
Styled Nicknames
Frostiful
Macaw's Fences and Walls
Mermod
oωo
Trenzalore
No Chat Reports
Resourcefulconfig
Macaw's Bridges
Medieval Origins Revival
Lithium
FTB Library
Cloth Config v11
Energized Power
QuarryPlus
Origins Minus
SuperMartijn642's Config Lib
WI Zoom
Load My F***ing Tags
Cardinal Components API
Entity Model Features
Autofish
Scalable Cat's Force Fabric
Origins: Genders
Eccentric Tome
Modern Dynamics
BotanyTrees
Wildfire's Female Gender Mod
Connected Glass
Spectrum
Tax Free Levels
Moving Elevators
AdvancementInfo
YUNG's Better Mineshafts
YUNG's Better Strongholds
Powah!
Coins
ToolTip Fix
Polymorphic Energistics
Bad Packets
Styled Player List
Create: Metalwork
Rebind Narrator
Flux Networks
SuperMartijn642's Core Lib
Tom's Simple Storage Mod
piercingpaxels
TerraBlender
Boat Item View Fabric
YUNG's Better Ocean Monuments
Inventory Sorter
Krypton
Prism
Create Deco
Litematica
Kibe
Lithostitched
AE2WTLib
Handcrafted
Animatica
Sodium
Fusion
Delightful Creators
Thermoo
Icarus
Fabric Waystones
Shulker Box Tooltip
Journeymap
Clumps
Fullblock Energistics
Reese's Sodium Options
MidnightLib
Trading Post
DebugKeybind
CompleteConfig
Athena
Continuity
Create Crafts & Additions
Create Enchantment Industry
AlmostUnified
Create Slice & Dice
Better Statistics Screen
Create: Copycats+
Create: Steam 'n' Rails
Expanded Storage
ForgeLikeVersionChecker
GeckoLib 4
Mythic Metals
Moonlight
Industrial Revolution
Puzzles Lib
Scorchful
Simple Voice Chat
YUNG's Better Jungle Temples (Fabric)
YUNG's Better Nether Fortresses
Wood You Dye Companion
YUNG's Better End Island
Create Fabric
Ad Astra
Compressor
Chassis

**Comment by Librv** [comment]
Is this a public modpack? That would make the process quicker, otherwise just list the minecraft version you're running.

**Comment by CassieRoseZA** [comment]
[latest(2).log](https://github.com/EvergoodTeam/Compressor/files/14731394/latest.2.log)

**Comment by CassieRoseZA** [comment]
> Is this a public modpack? That would make the process quicker, otherwise just list the minecraft version you're running.

1.20.1 and no its a custom pack

**Comment by CassieRoseZA** [comment]
Ok it seems to have been a corrupt config folder

**Comment by Librv** [comment]
Try deleting the <code>compressor</code> folder in the configs directory (both on the server and your client) and let me know if it still crashes.

**Comment by CassieRoseZA** [comment]
i deleted the folder on server and its fine the client never crashed only server
