### ISSUE TITLE
Quilt support

### ISSUE THREAD

**Issue by SplendidAlakey** [Librv/Compressor#3]
Hello! Could you please add support for the [Quilt](https://quiltmc.org/) modloader? Normally, all Fabric mods are natively supported by Quilt (Chassis works with no issues), but Compressor is causing a crash on startup.

Logs: https://gist.github.com/Footage2-Amply-Pounce/ee1f4bd36318a395411e924ee6bf7cc7

**Comment by Librv** [comment]
I've just released an update to Chassis on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/chassis/files/3926780); replacing the old version (1.2.1) in your mod folder should be enough. 
If any other issue pops up, let me know, and thanks for reporting this one!
