### ISSUE TITLE
Compressor 0.1.1+ shows Chassis as an embedded library rather than a required dependency

### ISSUE THREAD

**Issue by Mr1cecream** [Librv/Compressor#5]
**Description**
Compressor 0.1.1+ shows Chassis as an embedded library rather than a required dependency.

See bottom of screenshot
![image](https://user-images.githubusercontent.com/88837169/195874762-8734ec35-084f-4839-8ae3-045e180d6b26.png)

This affects Third-party mod manager that use CurseForge's API to determine dependencies, which see Chassis as an embedded library and therefore do not download the required jar automatically.

**Comment by Librv** [comment]
Thanks for pointing this out, should be fixed now for both Compressor and Chassis (which requires the Fabric API).
