### ISSUE TITLE
Add wither-proof blocks

### ISSUE THREAD

**Issue by Pultex** [Librv/Compressor#6]
Just to have an option that could be turned off in config
to have the option to have sort of wither proof option to be used in automation setups to mobs or bosses

not sure if after an amount of hardness the block break mechanic stop effecting the block

only thing with that is with some mod bosses they can cause blocks to break like a command block
similar to the effects of Botania that can use lens to effect any block unless blacklisted [bedrock block]

modded bosses only work as summons so it would allow for a floor to fight on that is not at the bottom of the world map

having this would just be tool to add the mechanic to fabric/Quilt as have not seen it in other mods for those mod loaders

**Comment by Librv** [comment]
How does the idea of having all the octuple compressed blocks be wither-resistant? I think that's a balanced way to offer the player the option to encase bosses, I'll have to test this to see if it also applies to modded bosses.

**Comment by Librv** [comment]
Done as of https://github.com/EvergoodTeam/Compressor/commit/55115a5062fc4fe486af60c68d46a28e1ab84ec5, versions older than 1.20 may not have this.
