### ISSUE TITLE
Add Tuff and Calcite

### ISSUE THREAD

**Issue by Oliver-Habersetzer** [Librv/Compressor#7]
Heyo!

Please add some of the new materials to be able to compress tuff, calcite and the other stone like blocks as well - that would be awesome <3
![image](https://user-images.githubusercontent.com/42864929/220485360-baf8584f-df3f-440d-ae01-8647dfd68d06.png)
![image](https://user-images.githubusercontent.com/42864929/220485387-a7602b64-f171-4a66-bc41-89067803b45a.png)

Thanks for the great work!
Cheers

**Comment by Librv** [comment]
Done as of https://github.com/EvergoodTeam/Compressor/commit/2364333021fcf04d562c34c9b9e21e92189779d2, should release in the weekend, sorry for the long wait!
