### ISSUE TITLE
Textures missing on 0.3.2

### ISSUE THREAD

**Issue by plantiac** [Librv/Compressor#9]
Title says it.
Used to work before the update.
I play 'All of Fabric 6' + some additional mods

Output log: [latest.log](https://github.com/EvergoodTeam/Compressor/files/11502885/latest.log)

**Comment by Librv** [comment]
Try deleting the `compressor` folder inside the `config` directory. It probably wasn't updated because the configs locked the resources from being regenerated with the new assets.

**Comment by plantiac** [comment]
Thanks, this resolved the issue 👍
